# This is a basic workflow to help you get started with Actions

name: CI




# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["First_Workflow-unit_tests"]
    types:
      - completed
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}  # Reference secret as an environment variable
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}  # Reference secret as an environment variable

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run docker file
        run: docker compose up -d
      - name: wait 60 seconds
        run: sleep 60
      - name: check 
        run: curl -XGET http://localhost:5000
            
